import Foundation

// MARK: - What an agent is doing right now
//
// Three signals, deliberately separate:
//
//   phase    — parsed straight out of Claude's status line ("✻ Incubating… (2m 20s ·
//              ↓ 6.1k tokens)"). Free, exact, updates every second.
//   activity — a one-clause description generated by a small local model from the
//              visible screen. Slow, approximate, but says what the work *is*.
//   background — shells and subagents still running, read off whichever surface the
//              agent puts them on. Unlike the other two this survives the turn, which
//              is the only reason it is worth having: it is what an *idle* card says.
//
// Neither replaces the terminal title; they sit under it.

struct Phase: Encodable {
    var verb: String        // "Incubating"
    var elapsed: String?    // "2m 20s"
    var tokens: String?     // "6.1k"
    var thinking: Bool
}

/// Work the agent started and then handed the prompt back on — a background shell, a
/// background agent. Deliberately not folded into `phase`: phase says the agent itself
/// is busy and dies the moment it answers you, while this outlives the turn. That gap is
/// the whole bug it exists to close — an agent can be idle, waiting on you, with six
/// research runs still in flight, and the card said nothing.
struct BackgroundWork: Encodable, Equatable {
    var kind: String        // "shell" | "agent" | "task"
    var count: Int
}

/// The state of play on a card: three short fields from the latest reply. `ask` is the
/// one that changes what you do — it is the question the agent has stopped on.
struct Outcome: Encodable, Equatable {
    var done: String?
    var next: String?
    var ask: String?

    /// The one-string form the summariser stores and logs; `parseOutcome` reads it back.
    var serialised: String {
        ["DONE: \(done ?? "-")", "NEXT: \(next ?? "-")", "ASK: \(ask ?? "-")"]
            .joined(separator: "\n")
    }
}

extension HerdrSource {
    /// `--source visible` is the only source that works on a *working* agent — `recent`
    /// refuses with agent_not_idle, because alternate-screen history can only be
    /// captured by scrolling while idle. Visible is exactly what we want anyway.
    /// Throttled per pane: the phase timer only needs about a second of resolution, while
    /// ticks are event-driven and a burst of Herdr events can fire several inside one
    /// second — each of which would otherwise spawn a subprocess per working agent.
    private static let screenLock = NSLock()
    nonisolated(unsafe) private static var lastScreenRead: [String: Date] = [:]

    /// Pane-keyed, so it is pruned to the live panes each tick like the other caches.
    static func retainScreenReads(panes: Set<String>) {
        screenLock.lock(); defer { screenLock.unlock() }
        lastScreenRead = lastScreenRead.filter { panes.contains($0.key) }
    }

    func visibleScreenThrottled(pane: String, minInterval: TimeInterval = 1.0,
                                lines: Int = 40) -> String? {
        Self.screenLock.lock()
        if let t = Self.lastScreenRead[pane], Date().timeIntervalSince(t) < minInterval {
            Self.screenLock.unlock()
            return nil
        }
        Self.lastScreenRead[pane] = Date()
        Self.screenLock.unlock()
        return visibleScreen(pane: pane, lines: lines)
    }

    func visibleScreen(pane: String, lines: Int = 40) -> String? {
        guard let data = try? Shell.run(
            binary, ["agent", "read", pane, "--source", "visible",
                     "--lines", String(lines), "--format", "text"]),
              let text = String(data: data, encoding: .utf8),
              !text.contains("\"code\":\"agent_not_idle\"")
        else { return nil }
        return text
    }
}

enum StatusLine {
    /// Matches "✻ Incubating… (2m 20s · ↓ 6.1k tokens · thought for 17s)".
    /// The glyph rotates and the verb changes constantly, so match structurally.
    static func parse(_ screen: String) -> Phase? {
        let pattern = #"[^\s\w]\s*([A-Z][a-z]+)…\s*\(([^)]*)\)"#
        guard let re = try? NSRegularExpression(pattern: pattern) else { return nil }
        let ns = screen as NSString
        let matches = re.matches(in: screen, range: NSRange(location: 0, length: ns.length))
        guard let m = matches.last, m.numberOfRanges >= 3 else { return nil }

        let verb = ns.substring(with: m.range(at: 1))
        let inner = ns.substring(with: m.range(at: 2))
        let parts = inner.components(separatedBy: "·").map {
            $0.trimmingCharacters(in: .whitespaces)
        }

        var elapsed: String?, tokens: String?
        for p in parts {
            if p.contains("token") {
                tokens = p.replacingOccurrences(of: "↓", with: "")
                    .replacingOccurrences(of: "tokens", with: "")
                    .replacingOccurrences(of: "token", with: "")
                    .trimmingCharacters(in: .whitespaces)
            } else if elapsed == nil, p.range(of: #"^\d"#, options: .regularExpression) != nil {
                elapsed = p
            }
        }
        return Phase(verb: verb, elapsed: elapsed, tokens: tokens,
                     thinking: inner.contains("thought for"))
    }
}

/// Background work has no single surface. Three agents were run side by side in Herdr
/// and prompted into every state, and they agree on nothing:
///
///   claude  a `·`-delimited segment in the hint line under the composer:
///             ⏵⏵ bypass permissions on · 1 shell · ← for agents · ↓ to manage
///           Subagents get a segment there too, but *without a count*:
///             ⏵⏵ bypass permissions on · /tasks to see subagents · ← for agents
///           and while the main loop is actually waiting on them, a status line that
///           does carry one, with the agent tree drawn under the footer:
///             ✻ Waiting for 1 background agent to finish
///   codex   its own live line above the composer, which disappears the moment the
///           process exits (verified by killing one):
///             2 background terminals running · /ps to view · /stop to close
///   pi3     nothing. Its footer is model, mode and context only, and a delegated
///           worker leaves no persistent mark. Nothing to read, so nothing is claimed.
///
/// The decisive case is a Claude pane at `done` with a subagent still going, where the
/// entire evidence is one countless hint segment:
///
///     ⏵⏵ bypass permissions on (shift+tab to cycle) · /tasks to see subagents · ← for agents
///
/// So a count is reported where one is offered and presence alone where it isn't —
/// `count == 0` means "running, and the agent didn't say how many".
enum BackgroundLine {
    /// Claude's hint line. Matched as a whole segment: "← for agents" is a keybinding
    /// hint on every Claude pane there is, and "Ran 2 shell commands" is scrollback
    /// prose. Anchoring on a leading digit with nothing after the noun excludes both.
    private static let shellSegment = re(#"^(\d+)\s+shells?$"#)
    /// Codex's line. Normalised to "shell" rather than kept as its own word: the chip is
    /// a deck-level idea, and "2 terminals" beside "2 shells" on adjacent cards reads as
    /// two different things happening rather than the same thing on two agents.
    private static let terminalSegment = re(#"^(\d+)\s+background terminals?\s+running$"#)
    /// Claude's status line while it waits on subagents — the one surface that counts
    /// them. Searched anywhere in the line, since it opens with a rotating glyph.
    private static let waitingLine = re(#"Waiting for (\d+) background agents?\s+to finish"#)
    /// Claude's countless subagent segment.
    private static let subagentHint = "/tasks to see subagents"

    private static func re(_ pattern: String) -> NSRegularExpression? {
        try? NSRegularExpression(pattern: pattern)
    }

    private static func number(_ re: NSRegularExpression?, in text: String) -> Int? {
        guard let re else { return nil }
        let ns = text as NSString
        guard let m = re.firstMatch(in: text, range: NSRange(location: 0, length: ns.length)),
              m.numberOfRanges >= 2
        else { return nil }
        return Int(ns.substring(with: m.range(at: 1)))
    }

    /// Only the tail of the screen is read. Every signal above lives in a region the
    /// agent redraws, while the scrollback right above it is full of sentences that
    /// were true when written and never again — "✻ Brewed for 2m 0s · 1 shell still
    /// running" sits there long after that shell has exited. Fourteen lines, because
    /// Claude's tree pushes the status line that far up from the bottom.
    static func parse(_ screen: String, tail: Int = 14) -> [BackgroundWork] {
        var shells = 0
        var subagents = 0
        var subagentsRunning = false

        for line in screen.components(separatedBy: .newlines).suffix(tail) {
            if line.contains(subagentHint) { subagentsRunning = true }
            if let n = number(waitingLine, in: line), n > 0 {
                subagentsRunning = true
                subagents = max(subagents, n)
            }
            var candidates = [line.trimmingCharacters(in: .whitespaces)]
            if line.contains("·") {
                candidates += line.components(separatedBy: "·")
                    .map { $0.trimmingCharacters(in: .whitespaces) }
            }
            for candidate in candidates {
                if let n = number(shellSegment, in: candidate) { shells = max(shells, n) }
                if let n = number(terminalSegment, in: candidate) { shells = max(shells, n) }
            }
        }

        var work: [BackgroundWork] = []
        if shells > 0 { work.append(BackgroundWork(kind: "shell", count: shells)) }
        if subagentsRunning { work.append(BackgroundWork(kind: "subagent", count: subagents)) }
        return work
    }

    /// "1 shell", "2 shells · subagents", "1 shell · 2 subagents" — pluralised here so
    /// the client only ever renders. A kind with no count prints as the bare plural
    /// rather than inventing a "1", which would be a claim the agent never made.
    static func summary(_ work: [BackgroundWork]) -> String? {
        guard !work.isEmpty else { return nil }
        return work
            .map { $0.count == 0
                ? "\($0.kind)s"
                : "\($0.count) \($0.kind)\($0.count == 1 ? "" : "s")" }
            .joined(separator: " · ")
    }
}

// MARK: - Local model summariser

/// Generates short activity labels with Ollama. Everything about this is defensive:
/// the dashboard must never block, stall, or stampede the model.
///
///  - Only working agents are summarised; idle ones keep their terminal title.
///  - A screen whose text hasn't changed is never re-sent.
///  - One request in flight at a time, globally.
///  - Per-pane cooldown, so a chatty agent can't monopolise the model.
///  - Every failure is silent and simply leaves the previous label in place.
final class Summariser {
    struct Entry {
        var label: String
        var screenHash: Int
        var updated: Date
    }

    private let queue = DispatchQueue(label: "agentdeck.summarise")
    private let lock = NSLock()
    private var cache: [String: Entry] = [:]
    private var names: [String: Entry] = [:]
    private var inFlight = false

    let model: String
    /// Defaults to `model`; --title-model splits them. Titles regenerate once every few
    /// prompts, so they *can* afford a slower model than the per-prompt subtitle and
    /// outcome jobs — but one model for all three won on quality and on resident memory,
    /// so the split is an option rather than the arrangement in use.
    let titleModel: String
    let modelMonitor: LocalModelMonitor?
    let cooldown: TimeInterval
    let endpoint: URL

    init(model: String, titleModel: String? = nil, cooldown: TimeInterval = 20,
         endpoint: String = "http://127.0.0.1:11434",
         modelMonitor: LocalModelMonitor? = nil) {
        self.model = model
        self.titleModel = titleModel ?? model
        self.cooldown = cooldown
        self.endpoint = URL(string: endpoint + "/api/chat")!
        self.modelMonitor = modelMonitor
    }

    func label(for pane: String) -> String? {
        lock.lock(); defer { lock.unlock() }
        return cache[pane]?.label
    }

    /// Fire-and-forget. Returns immediately; the label appears on a later poll.
    func consider(pane: String, screen: String) {
        let hash = screen.hashValue

        lock.lock()
        let entry = cache[pane]
        let fresh = entry?.screenHash == hash
        let cooling = entry.map { Date().timeIntervalSince($0.updated) < cooldown } ?? false
        let busy = inFlight
        if fresh || cooling || busy { lock.unlock(); return }
        inFlight = true
        lock.unlock()

        queue.async { [weak self] in
            guard let self else { return }
            let result = self.generate(screen: screen, pane: pane)
            self.lock.lock()
            self.inFlight = false
            if let label = result {
                self.cache[pane] = Entry(label: label, screenHash: hash, updated: Date())
            } else {
                // Record the attempt so a failing model isn't retried every tick.
                var e = self.cache[pane] ?? Entry(label: "", screenHash: hash, updated: Date())
                e.updated = Date()
                e.screenHash = hash
                self.cache[pane] = e
            }
            self.lock.unlock()
        }
    }

    /// Drop panes that no longer exist so the caches can't grow without bound.
    func retain(panes: Set<String>) {
        lock.lock(); defer { lock.unlock() }
        cache = cache.filter { panes.contains($0.key) }
        names = names.filter { panes.contains($0.key) }
        subtitles = subtitles.filter { panes.contains($0.key) }
        states = states.filter { panes.contains($0.key) }
        promptsSeen = promptsSeen.filter { panes.contains($0.key) }
        titleAt = titleAt.filter { panes.contains($0.key) }
    }

    // MARK: - Title and subtitle, from the transcript
    //
    // Two jobs at two cadences, because the two answers go stale at different rates:
    //
    //   title    the overall task. Claude sets its own equivalent once from the opening
    //            message and never revisits it — accurate at minute five, wrong 34 hours
    //            later. So this regenerates, but only every `titleEvery` prompts.
    //   subtitle where the last five turns have got to. Regenerates once per prompt,
    //            keyed on the text of the latest user turn rather than file mtime.

    /// Set alongside each considerNames call so log lines can carry which session and
    /// agent a heading came from, not just a pane id that dies with the pane.
    private var logContext: [String: (session: String?, agent: String)] = [:]

    private var subtitles: [String: Entry] = [:]
    private var states: [String: Entry] = [:]
    private var promptsSeen: [String: Int] = [:]
    private var titleAt: [String: Int] = [:]

    let titleEvery = 8

    /// How many prompts to wait before re-titling, given how many have been seen.
    ///
    /// A fixed interval titled a session exactly once — at the moment there was least
    /// evidence — and then left it alone for eight prompts. Short sessions suffered
    /// worst: with two or three turns there is nothing to weigh, so the newest request
    /// dominates and the title describes the last exchange rather than the job
    /// ("Analyze swap file status" for a session about memory and model choice).
    ///
    /// Re-title every prompt while history is thin, occasionally as it fills, rarely
    /// once it has settled, so the title converges as the conversation continues
    /// instead of being fixed by its first two turns. This counts real user requests,
    /// so pi and codex sessions improve exactly as Claude's do — no agent special-cased.
    func titleInterval(promptsSeen count: Int) -> Int {
        if count < 4 { return 1 }
        if count < 12 { return 3 }
        return titleEvery
    }

    /// Records which session and agent a pane belongs to, so log lines survive the
    /// pane id — pane ids die with the pane, session paths don't.
    func setLogContext(pane: String, session: String?, agent: String) {
        lock.lock(); defer { lock.unlock() }
        logContext[pane] = (session, agent)
    }

    // The subscript runs under the lock as well as the emptiness test: the summarise
    // queue rewrites these dictionaries, and a read on the poll queue that raced a
    // resize was a crash waiting for a busy enough afternoon.
    func name(for pane: String) -> String? { read { $0.names[pane]?.label } }
    func subtitle(for pane: String) -> String? { read { $0.subtitles[pane]?.label } }
    func state(for pane: String) -> String? { read { $0.states[pane]?.label } }

    private func read(_ get: (Summariser) -> String?) -> String? {
        lock.lock(); defer { lock.unlock() }
        let s = get(self)
        return (s?.isEmpty ?? true) ? nil : s
    }

    /// Transcript-driven, so it works for idle agents too — which is what finally gives
    /// pi and codex real titles instead of a tab label.
    func considerNames(pane: String, digest: TranscriptDigest) {
        let key = digest.lastPromptKey

        lock.lock()
        if inFlight { lock.unlock(); return }

        let seen = promptsSeen[pane] ?? 0
        let isNewPrompt = subtitles[pane]?.screenHash != key
        let count = isNewPrompt ? seen + 1 : seen
        if isNewPrompt { promptsSeen[pane] = count }

        // A new prompt makes the previous outcome wrong: it describes work you have
        // already moved past. Clear it and leave the card without an outcome until the
        // agent actually replies, rather than showing a stale "the work is complete".
        if isNewPrompt { states[pane] = nil }

        // A title that fails to generate leaves an empty entry behind, and that entry
        // used to be permanent: it is non-nil, so the "never titled" test stopped
        // firing, and the interval below counts real user requests — which a session
        // whose every prompt is filtered out never accumulates. One `/goal` session sat
        // under Herdr's fallback title for its whole life on exactly that path. An empty
        // title is retried on the same cooldown the activity label uses, so a model that
        // is simply down still can't be hammered.
        let named = names[pane]
        let needsTitle = (named?.label.isEmpty ?? true)
            ? named.map { Date().timeIntervalSince($0.updated) >= cooldown } ?? true
            : (count - (titleAt[pane] ?? 0)) >= titleInterval(promptsSeen: count)
        let needsSubtitle = isNewPrompt
        // Keyed on the reply itself, so this regenerates exactly when a turn completes.
        let needsState = !digest.lastReply.isEmpty
            && states[pane]?.screenHash != digest.lastReplyKey
        guard needsTitle || needsSubtitle || needsState else { lock.unlock(); return }
        inFlight = true
        if needsTitle { titleAt[pane] = count }
        lock.unlock()

        queue.async { [weak self] in
            guard let self else { return }
            var newTitle: String?
            var newSubtitle: String?
            var newState: String?
            if needsState { newState = self.generateState(digest, pane: pane, promptsSeen: count) }
            if needsTitle { newTitle = self.generateTitle(digest, pane: pane, promptsSeen: count) }
            if needsSubtitle {
                // Hand the model the current title so it can say something *else*.
                // Without it, subtitles just paraphrase the title back.
                newSubtitle = self.generateSubtitle(digest, title: newTitle ?? self.name(for: pane),
                                                   pane: pane, promptsSeen: count)
            }

            self.lock.lock()
            self.inFlight = false
            if needsTitle {
                var e = self.names[pane] ?? Entry(label: "", screenHash: 0, updated: Date())
                e.updated = Date()
                if let t = newTitle { e.label = t }   // keep the old one on failure
                self.names[pane] = e
            }
            if needsSubtitle {
                var e = self.subtitles[pane] ?? Entry(label: "", screenHash: key, updated: Date())
                e.screenHash = key
                e.updated = Date()
                if let s = newSubtitle { e.label = s }
                self.subtitles[pane] = e
            }
            if needsState {
                var e = self.states[pane]
                    ?? Entry(label: "", screenHash: digest.lastReplyKey, updated: Date())
                e.screenHash = digest.lastReplyKey
                e.updated = Date()
                if let s = newState { e.label = s }
                self.states[pane] = e
            }
            self.lock.unlock()
        }
    }

    /// The job where the prompt has to name a decision rather than state a preference.
    ///
    /// Evaluated against ten hand-written reference titles taken from real sessions cut
    /// at a mid-point. Three of the ten had *drifted*: the session opened with one
    /// question ("check today's research run", "I've connected an ESP32") and had since
    /// settled on a different, larger problem. The shipped prompt said "weight the
    /// opening request most heavily", so it named the abandoned question on every one
    /// of those — which is why the headings looked wrong.
    ///
    /// Telling the model to find the recurring theme instead just moved the failure: it
    /// then latched onto the most recent request on the sessions that had *not* drifted.
    /// Naming the choice explicitly — is this still about the opening, or did it move
    /// on? — is what fixed both. gemma4:12b scored ~8/10 with it; qwen3:4b-instruct
    /// fixed the drift cases but regressed easy ones, and gemma4:e4b hallucinated.
    private func generateTitle(_ d: TranscriptDigest, pane: String,
                               promptsSeen: Int) -> String? {
        // User requests only — no agent prose. The agent's replies describe whatever it
        // was doing minutes ago, which pulled titles toward recent activity and made
        // them collide with the subtitle.
        let prompt = """
        A user opened a working session with one request, then continued.

        FIRST REQUEST:
        \(String(d.opening.prefix(400)))

        LATER REQUESTS:
        \(String(d.requests.prefix(1200)))

        Decide which of these two is true:
        (a) The later requests are follow-ups that serve the FIRST request — the session
            is still about the thing it opened with.
        (b) The first request was answered or set aside early, and most later requests
            are about a DIFFERENT problem the session then settled on.

        If (a), name the first request's goal. If (b), name that different problem.
        Do not name whatever the most recent single request happens to be.

        If there are only one or two later requests, there is not yet enough evidence
        that the session has moved on — name the first request's goal.

        Name the subject the user is working on, not the assistant's response to it.
        Never describe replying, greeting, acknowledging, helping or answering.

        Answer with only a 3 to 6 word imperative task name. No quotes. No trailing period.

        NAME:
        """
        guard let s = call(prompt: prompt, maxTokens: 40, model: titleModel,
                           kind: "title", pane: pane, promptsSeen: promptsSeen)
        else { return nil }
        guard Self.namesWork(s) else {
            Self.debug("rejected title: describes the assistant's reply — \(s)")
            HeadingLog.record(HeadingRecord(
                ts: HeadingLog.stamp(), pane: pane, session: nil, agent: "?",
                kind: "title", model: titleModel, promptsSeen: promptsSeen, ms: 0,
                accepted: false, reason: "assistant-action", text: s))
            return nil
        }
        return s
    }

    /// The heading that has to name the *step*, not the job — and the one the latest
    /// request is often incapable of naming on its own.
    ///
    /// Measured on the running deck's own log: **37% of the prompts that trigger a
    /// subtitle are eight words or fewer**. "ok run that", "no that doesn't work",
    /// "sure check please" all pass `carriesIntent` — they are real requests, not
    /// pleasantries — so a subtitle is generated from an input naming no work at all.
    /// Handed only those, the model wrote "Software installation", "Approve tapped
    /// status", and for "ok bypass everyone for inbox" the actively wrong "Bypass all
    /// recipients for inbox messages" — it read Cloudflare Access as email recipients.
    ///
    /// The step such an answer sets in motion is in the turn *before* it, so the
    /// preceding reply is now in the prompt, with two worked examples pinning the
    /// grain. Evaluated over 20 replayed sessions × 3 checkpoints × 3 repeats
    /// (`Evals/subtitle`), hand-scored on the 17 thin-prompt checkpoints: 0.65 → 1.41
    /// out of 2, with useless subtitles falling from 8 of 17 to 2 of 17. On prompts
    /// that already named work it is a wash (−0.02), so this costs nothing where the
    /// old prompt was already fine.
    ///
    /// Rejected on the way: an "atomic step" reframing *without* the added context
    /// scored below the shipped prompt, and a forced `<verb> <object>` shape scored
    /// worst of seven — the gain is the inputs, not the phrasing. Loosening
    /// `distinct` to admit the one good subtitle it costs was tested against the
    /// production log and would have shipped 22 of 24 real rejections, so the gate
    /// stays as it is.
    private func generateSubtitle(_ d: TranscriptDigest, title: String?,
                                  pane: String, promptsSeen: Int) -> String? {
        let goal = title ?? "the session's larger goal"
        // The reply the user is answering. Context only — the prompt has to say so,
        // or a short turn produces a description of the agent's own last message.
        let context = d.lastReply.isEmpty ? "" : """

            WHAT THE AGENT SAID JUST BEFORE THIS REQUEST (context only — do not
            describe the agent's reply itself, only the work it is about):
            \(String(d.lastReply.prefix(900)))

            """
        // Lead with the latest request. Asked about "recent turns" in general the model
        // reaches for the overall project and gets rejected as redundant.
        let source = d.lastPrompt.isEmpty
            ? "RECENT TURNS:\n\(String(d.recent.prefix(1200)))"
            : "LATEST REQUEST:\n\(String(d.lastPrompt.prefix(700)))"
        let prompt = """
        A working session is moving through a series of requests toward one larger goal.
        Name the single concrete step now underway in service of that goal.

        Two examples of the right size and shape:

          GOAL: Migrate the photo library to Postgres
          REQUEST: "the thumbnails are all coming out rotated 90 degrees"
          STEP: Fix rotated thumbnails in the importer

          GOAL: Tune the espresso grinder settings
          CONTEXT: the agent had just asked for a shot pulled at a finer grind
          REQUEST: "ok pulled it"
          STEP: Read the shot time at the finer grind

        Notice the second one: a short answer names no work by itself, so the step comes
        from what the answer sets in motion.

        THE LARGER GOAL: \(goal)
        \(context)
        \(source)

        One action on one thing, at most 8 words. Never restate the goal. Write
        impersonally, never "you" or "I". Name the subject of the work, not the
        assistant's response to it. No quotes, no trailing period.

        STEP:
        """
        // 130 rather than the 90-char default: with real user prompts now reaching the
        // model, subtitles got more specific and longer, and the cap was silently
        // discarding them — the same failure that killed every state summary earlier.
        guard let s = call(prompt: prompt, maxTokens: 32, maxChars: 130,
                           kind: "subtitle", pane: pane, promptsSeen: promptsSeen)
        else { return nil }
        guard Self.namesWork(s) else {
            Self.debug("rejected subtitle: describes the assistant's reply — \(s)")
            HeadingLog.record(HeadingRecord(
                ts: HeadingLog.stamp(), pane: pane, session: nil, agent: "?",
                kind: "subtitle", model: model, promptsSeen: promptsSeen, ms: 0,
                accepted: false, reason: "assistant-action", text: s))
            return nil
        }
        // Telling a 3b model not to restate the title only half works — it answers
        // "<title> is being developed now". A redundant subtitle is worse than none.
        guard Self.distinct(s, from: title) else {
            Self.debug("rejected subtitle: too close to title — \(s)")
            HeadingLog.record(HeadingRecord(
                ts: HeadingLog.stamp(), pane: pane, session: nil, agent: "?",
                kind: "subtitle", model: model, promptsSeen: promptsSeen, ms: 0,
                accepted: false, reason: "too-close-to-title", text: s))
            return nil
        }
        return s
    }

    /// The state of play, from the agent's most recent reply, as three labelled lines:
    /// what got done, what comes next, and the question the agent is waiting on. This is
    /// the block that answers "does this one need me?", and it used to be asked for as
    /// three sentences of prose. Three sentences from a reply read in isolation came out
    /// as "The agent identified five pending tasks…" followed by "No decisions are
    /// pending" — 73% of outcomes in the log carried a sentence that said nothing, and
    /// 47% opened by naming the agent. Labelled clauses with the user's own request as
    /// context are shorter, land on the card as three scannable rows, and make the open
    /// question a field the deck can show on its own rather than prose it has to hope
    /// you read to the end of.
    private func generateState(_ d: TranscriptDigest, pane: String,
                               promptsSeen: Int) -> String? {
        let context = d.lastPrompt.isEmpty
            ? ""
            : "THE USER HAD ASKED FOR:\n\(String(d.lastPrompt.prefix(300)))\n\n"
        let prompt = """
        A coding agent has just replied to its user. Write three lines for a status card
        the user reads at a glance, in this exact form:

        DONE: what this reply accomplished. One clause, at most 14 words, using the
        concrete names from the reply (files, notes, functions, chapters).
        NEXT: what the agent said it will do next or proposed doing. One clause, at
        most 14 words. Write - if it named nothing.
        ASK: what the reply is waiting on the user for — a question it asked, a choice
        it left open ("pending your choice", "let me know", "which do you prefer"), or
        approval it needs. Phrase it as one question ending in ?, at most 16 words.
        Write - if the reply is not waiting on the user for anything.

        Never write "the agent", "the user", "you" or "I". No preamble, no other lines.
        Do not invent a question: ASK is - unless the reply is genuinely waiting on the user.

        \(context)THE AGENT REPLIED:
        \(String(d.lastReply.prefix(1400)))

        DONE:
        """
        // The three lines together; the parser below splits them back out. 600 is above
        // anything the token budget can produce, so tidy's sentence trimming never fires
        // on this shape and cuts the ASK line off the end.
        guard let raw = call(prompt: prompt, maxTokens: 150, maxChars: 600, multiline: true,
                             kind: "outcome", pane: pane, promptsSeen: promptsSeen)
        else { return nil }
        // The prompt ends in "DONE:", so the model's first line is usually the bare clause.
        let text = raw.range(of: "DONE:", options: .caseInsensitive) == nil
            ? "DONE: " + raw : raw
        guard let outcome = Self.parseOutcome(text) else { return nil }
        return outcome.serialised
    }

    /// Splits "DONE: … NEXT: … ASK: …" — on one line or three — into its fields, dropping
    /// placeholders and any ASK that is not actually a question. Nil when nothing useful
    /// survives.
    static func parseOutcome(_ text: String) -> Outcome? {
        var fields: [String: String] = [:]
        let labels = ["DONE", "NEXT", "ASK"]
        // Positions of each label in order of appearance; each field runs to the next.
        var marks: [(label: String, range: Range<String.Index>)] = []
        for label in labels {
            var searchFrom = text.startIndex
            while let r = text.range(of: label + ":", options: .caseInsensitive,
                                     range: searchFrom..<text.endIndex) {
                marks.append((label, r))
                searchFrom = r.upperBound
            }
        }
        marks.sort { $0.range.lowerBound < $1.range.lowerBound }
        for (i, m) in marks.enumerated() {
            let end = i + 1 < marks.count ? marks[i + 1].range.lowerBound : text.endIndex
            let value = clause(String(text[m.range.upperBound..<end]))
            if let value, fields[m.label] == nil { fields[m.label] = value }
        }
        var ask = fields["ASK"]
        if let a = ask, !a.hasSuffix("?") || a.count < 8 { ask = nil }
        let o = Outcome(done: fields["DONE"], next: fields["NEXT"], ask: ask)
        return o.done == nil && o.next == nil && o.ask == nil ? nil : o
    }

    /// One field's text, or nil when it is a placeholder or names the agent.
    private static func clause(_ raw: String) -> String? {
        var s = raw.trimmingCharacters(in: .whitespacesAndNewlines)
            .trimmingCharacters(in: CharacterSet(charactersIn: "\"'`“” -–—•*"))
        s = s.replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
        if s.hasSuffix(".") { s = String(s.dropLast()) }
        let lowered = s.lowercased()
        let placeholders: Set<String> = ["", "-", "—", "n/a", "none", "nothing", "no",
                                         "not applicable", "nothing pending", "no decision",
                                         "no decisions", "no question", "no questions"]
        if placeholders.contains(lowered) || s.count < 3 { return nil }
        if lowered.hasPrefix("the agent ") || lowered.hasPrefix("the user ") { return nil }
        return String(s.prefix(160))
    }

    /// True when a heading names the user's work rather than the assistant's reply to it.
    ///
    /// The prompts now forbid this phrasing, but a 12b model asked for an imperative when
    /// the turn was a pleasantry has nothing else to reach for, and produces "Greet user
    /// and start conversation" or "Acknowledge user update and personal reflections".
    /// Filtering pleasantries out of the transcript removes most of the cause; this
    /// catches the rest deterministically, because a heading that reads as an instruction
    /// to the agent is worse than no heading at all — the card falls back to the
    /// terminal title, which is at least the user's own words.
    static func namesWork(_ heading: String) -> Bool {
        let first = heading.lowercased()
            .components(separatedBy: CharacterSet.alphanumerics.inverted)
            .first { !$0.isEmpty } ?? ""
        // Only verbs whose object is necessarily the conversation itself. "Discuss" and
        // "confirm" are left out: "Discuss chapter 4 structure" names real work.
        let assistantActions: Set<String> = [
            "greet", "greeting", "greets", "acknowledge", "acknowledging", "acknowledges",
            "respond", "responding", "reply", "replying", "answer", "answering",
            "assist", "assisting", "help", "helping", "welcome", "welcoming",
            "thank", "thanking", "apologize", "apologise", "chat", "chatting",
            "converse", "conversing", "engage", "engaging", "introduce", "introducing",
        ]
        return !assistantActions.contains(first)
    }

    /// True when the subtitle says something the title doesn't.
    static func distinct(_ subtitle: String, from title: String?) -> Bool {
        guard let title else { return true }
        func words(_ s: String) -> Set<String> {
            Set(s.lowercased()
                .components(separatedBy: CharacterSet.alphanumerics.inverted)
                .filter { $0.count > 3 })
        }
        let t = words(title)
        guard !t.isEmpty else { return true }
        let shared = t.intersection(words(subtitle)).count
        return Double(shared) / Double(t.count) < 0.6
    }

    private func generate(screen: String, pane: String = "?") -> String? {
        let tail = String(screen.suffix(2000))
        let prompt = """
        You are labelling a coding agent's terminal for a status dashboard.
        Reply with ONE clause, max 8 words, describing what the agent is doing right now.
        No punctuation at the end. No quotes. Present participle.

        TERMINAL:
        \(tail)

        LABEL:
        """
        return call(prompt: prompt, maxTokens: 24, kind: "activity", pane: pane)
    }

    /// Logs every generation, kept or discarded. `kind` and `pane` are optional so the
    /// activity path (which has no transcript) can log too.
    private func call(prompt: String, maxTokens: Int, model overrideModel: String? = nil,
                      maxChars: Int = 90, multiline: Bool = false,
                      kind: String = "?", pane: String = "?", promptsSeen: Int = 0) -> String? {
        let body: [String: Any] = [
            "model": overrideModel ?? model,
            // /api/chat, not /api/generate: it applies each model's own chat
            // template, and `think: false` is required for Gemma 4, which is a
            // thinking model by default and otherwise spends the whole token
            // budget on a reasoning block and returns empty content.
            "messages": [["role": "user", "content": prompt]],
            "think": false,
            "stream": false,
            // Keeps the model resident: cold load is ~14s, warm is 0.2–3.5s.
            "keep_alive": "30m",
            "options": [
                "temperature": 0.1,
                "num_predict": maxTokens,
                // Ollama otherwise allocates the model's full declared window —
                // llama3.2:3b claims 131072 tokens, which pinned 17.2 GB of KV cache
                // for a 2 GB model and pushed the machine into swap. Every prompt here
                // is well under 1k tokens: screen tail 2000 chars, transcript digest
                // ~1800, latest reply 1400, plus <90 tokens of output.
                "num_ctx": 4096,
            ],
        ]
        guard let data = try? JSONSerialization.data(withJSONObject: body) else { return nil }

        var req = URLRequest(url: endpoint)
        req.httpMethod = "POST"
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = data
        req.timeoutInterval = 25

        let started = Date()
        let sem = DispatchSemaphore(value: 0)
        var out: String?
        var raw = ""
        var rejection: String?
        var responseReceived = false
        modelMonitor?.beginCall()
        URLSession.shared.dataTask(with: req) { d, _, _ in
            defer { sem.signal() }
            guard let d,
                  let obj = try? JSONSerialization.jsonObject(with: d) as? [String: Any],
                  let message = obj["message"] as? [String: Any],
                  let text = message["content"] as? String else { return }
            responseReceived = true
            raw = text.trimmingCharacters(in: .whitespacesAndNewlines)
            out = Self.tidy(text, maxChars: maxChars, multiline: multiline)
            if out == nil { rejection = raw.count > maxChars ? "too-long" : "too-short-or-empty" }
        }.resume()
        _ = sem.wait(timeout: .now() + 30)
        let elapsedMs = Int(Date().timeIntervalSince(started) * 1000)
        modelMonitor?.finishCall(ms: elapsedMs, ok: responseReceived)

        // Log kept and discarded alike. A heading rejected by a guard never reaches the
        // screen, so without this the most interesting failures are invisible.
        let ctx = { () -> (String?, String) in
            self.lock.lock(); defer { self.lock.unlock() }
            let c = self.logContext[pane]
            return (c?.session, c?.agent ?? "?")
        }()
        HeadingLog.record(HeadingRecord(
            ts: HeadingLog.stamp(), pane: pane, session: ctx.0, agent: ctx.1,
            kind: kind, model: overrideModel ?? model, promptsSeen: promptsSeen,
            ms: elapsedMs,
            accepted: out != nil, reason: rejection,
            text: out ?? String(raw.prefix(400))))
        return out
    }

    /// Small models like to add quotes, trailing stops, or a "Label:" preamble.
    static func tidy(_ raw: String, maxChars: Int = 90, multiline: Bool = false) -> String? {
        var s = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        // Deliberately no "STEP:", though the subtitle prompt now ends with it: the
        // match is unanchored, so an outcome reading "Next step: run the migration"
        // would lose everything before it. In 360 generations the model never echoed
        // the cue, so the guard would only ever have cost something.
        for marker in ["LABEL:", "NAME:", "FOCUS:", "STATE:"] {
            if let r = s.range(of: marker, options: .caseInsensitive) {
                s = String(s[r.upperBound...]).trimmingCharacters(in: .whitespaces)
            }
        }
        if multiline {
            // Two sentences may arrive on two lines; keeping only the first loses half.
            s = s.components(separatedBy: .newlines)
                .map { $0.trimmingCharacters(in: .whitespaces) }
                .filter { !$0.isEmpty }
                .joined(separator: " ")
        } else {
            s = s.components(separatedBy: .newlines).first ?? s
        }
        s = s.trimmingCharacters(in: CharacterSet(charactersIn: "\"'`“” "))
        if !multiline { s = s.trimmingCharacters(in: CharacterSet(charactersIn: ". ")) }
        // Returning a bare nil for four different reasons is what hid the state-summary
        // bug for an hour, and then the subtitle one. Say why when asked.
        if s.count <= 3 { debug("rejected: too short (\(s.count))"); return nil }
        if s.count > maxChars {
            // For prose, an overrun is the model adding a third sentence past the limit.
            // Trimming to the last complete sentence beats discarding the whole thing —
            // and beats clipping mid-word, which is what it used to look like on screen.
            if multiline, let trimmed = lastCompleteSentence(in: s, within: maxChars) {
                debug("trimmed \(s.count) → \(trimmed.count) chars at sentence boundary")
                return trimmed
            }
            debug("rejected: \(s.count) chars > \(maxChars) — \(s.prefix(70))…")
            return nil
        }
        return s
    }

    private static func lastCompleteSentence(in s: String, within maxChars: Int) -> String? {
        let head = String(s.prefix(maxChars))
        guard let end = head.lastIndex(where: { $0 == "." || $0 == "!" || $0 == "?" })
        else { return nil }
        let out = String(head[...end]).trimmingCharacters(in: .whitespaces)
        return out.count > 20 ? out : nil
    }

    static let debugging = ProcessInfo.processInfo.environment["AGENTDECK_DEBUG"] == "1"

    static func debug(_ m: String) {
        guard debugging else { return }
        FileHandle.standardError.write(Data("[summariser] \(m)\n".utf8))
    }
}
